### ISSUE TITLE
Compilation failure on tip

### ISSUE THREAD

**Issue by kevinburkeotto** [keybase/go-keychain#19]
Using the following development version of Go:

```
$ go version
go version devel +bcf964de5e Tue Dec 5 16:47:21 2017 +0000 darwin/amd64
```

On MacOS Sierra version 10.12.6, I'm getting the following compilation errors:

```
./corefoundation.go:29: cannot use nil as type _Ctype_CFDataRef in return argument
./corefoundation.go:35: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDataCreate
./corefoundation.go:36: cannot convert nil to type _Ctype_CFDataRef
./corefoundation.go:37: cannot use nil as type _Ctype_CFDataRef in return argument
./corefoundation.go:61: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
./corefoundation.go:62: cannot convert nil to type _Ctype_CFDictionaryRef
./corefoundation.go:63: cannot use nil as type _Ctype_CFDictionaryRef in return argument
./corefoundation.go:74: cannot convert &keys[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
./corefoundation.go:74: cannot convert &values[0] (type *_Ctype_CFTypeRef) to type *unsafe.Pointer
./corefoundation.go:87: cannot use nil as type _Ctype_CFStringRef in return argument
```

This might be a problem in the Go compiler or standard library, I haven't investigated it at all yet. I can't reproduce the issue using Go 1.9.

**Comment by kevinburkeotto** [comment]
Probably related: https://github.com/keybase/go-keychain/issues/19

**Comment by randall77** [comment]
These all look like limitations of the fix tool.  After fixing with the current gofix, I see three kinds of compilation errors:

First, limitations of gofix's type checker:
```
	cfData := C.CFDataCreate(nil, p, C.CFIndex(len(b)))
```
We'd like to replace the `nil` with `0`, but we have no type information for `C.CFDataCreate`.  `go fix` works one file at a time, and `C.CFDataCreate` is not declared in this file.  So we can't know that its argument type (or the result type, for that matter) is one we wish to rewrite.
Unless we hardwire these functions?  There are probably a lot of them...
Or maybe we could run cgo on this file first, which would get us the function declaration for all the functions?  Hmmm....

Second, converting addresses of the CF*Ref types to `*unsafe.Pointer`.  We might be able to handle this, by introducing an additional cast (like `(*unsafe.Pointer)(unsafe.Pointer(&keys[0]))`).
```
		keys := make([]C.CFTypeRef, count)
		values := make([]C.CFTypeRef, count)
		C.CFDictionaryGetKeysAndValues(cfDict, (*unsafe.Pointer)(&keys[0]), (*unsafe.Pointer)(&values[0]))
```
Life would have been easier if `CFDictionaryGetKeysAndValues` was declared as taking `*CFTypeRef` instead of  `**void` for the `keys` and `values` parameters.  I guess a `CFDictionary` can hold non-CoreFoundation types in it.

Third, types that we should fix but are not `C.CF*Ref` types.  `macos.go` references a type called `C.SecAccessRef` which should probably be fixed also, as it is upcast to a `C.CFTypeRef`.  Never heard of this type before.  I wonder how many other cases are out there?
(also `C.SecTrustedApplicationRef`, `C.SecKeychainItemRef`, `C.SecKeychainRef`)
Maybe we do `C.*Ref`, not just `C.CF*Ref`?

**Comment by akalin-keybase** [comment]
This should all be fixed now. Please reopen if not!
