### ISSUE TITLE
Using SecClassInternetPassword

### ISSUE THREAD

**Issue by stephengroat** [keybase/go-keychain#36]
Any reason the library doesn't work with SecClassInternetPassword? Is there a specific reason this is limited for this library or is it a feature that would be appreciated?

**Comment by wolfeidau** [comment]
I am guessing that keybase only needed generic password.

I was also looking at adding support for this so I can use it in https://github.com/versent/saml2aws rather than the bespoke code I have now.

https://developer.apple.com/documentation/security/1393322-seckeychainaddinternetpassword?language=objc

**Comment by akalin-keybase** [comment]
Added via https://github.com/keybase/go-keychain/pull/37
